#cloud-config
disable_root: false
repo_update: true
repo_upgrade: all

packages:
 - git
 - default-jre
 - curl

runcmd:
 - curl -fsSL https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip -o terraform_1.6.5_linux_amd64.zip
 - unzip terraform_1.6.5_linux_amd64.zip
 - mv terraform /usr/local/bin/
 - curl -fsSL https://get.docker.com -o install-docker.sh
 - sh install-docker.sh
 - curl -fsSL https://cloud-octopus-agent.obs.cn-north-4.myhuaweicloud.com/latest/install-octopus-agent.sh -o install-octopus-agent.sh
 - bash install-octopus-agent.sh  -u true -c ${cluster_id} -r ${region} -f ${project_id} -h ${download_host} -n "$(hostname)" -w "/opt/$(hostname)" -g false -j false -b true -d false -z myhuaweicloud.com -a ${ak} -s ${sk}