---
version: 2.0
params:
  - name: PIPELINE_NUMBER
    value: ""
  - name: PIPELINE_ID
    value: ""
  - name: terraform_download_url
    value: "https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip"
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "git@codehub.devcloud.ap-southeast-3.huaweicloud.com:hfa00001/codearts-pipeline-agent-on-demand.git"
        branch: "main"
        lfs: false
        submodule: false
  BUILD:
  - sh:
      name: "Install Terraform"
      inputs:
        command: |
          echo ${AccessKey}
          echo ${EncryptedSecretKey}
          echo ${ClusterId}
          export HW_ACCESS_KEY=${AccessKey}
          export HW_SECRET_KEY=${SecretKey}
          export HW_REGION_NAME=${Region}
          curl -fsSL ${Terraform_URL} -o terraform.zip
          unzip terraform.zip
          ./terraform init
          ./terraform apply -auto-approve -var="accesskey=${AccessKey}" -var="encryptedsecretkey=${EncryptedSecretKey}" -var="codearts_clusterid=${ClusterId}" -var="codearts_token=${AgentToken}"
  - upload_artifact:
      inputs:
        version: ${PIPELINE_ID}-${PIPELINE_NUMBER}
        path: terraform.tfstate